services:
  mongo:
    image: mongo
    container_name: movies-mongo
    ports:
      - '127.0.0.1:27017:27017'
    volumes:
      - mongo-data:/data/db
    networks:
      - proxy-net

  redis:
    image: redis
    container_name: movies-redis
    ports:
      - '127.0.0.1:6379:6379'
    volumes:
      - redis-data:/data
    networks:
      - proxy-net

  backend:
    image: abdullah048/portfolio:movie-backend
    container_name: movies-backend
    expose:
      - '8000'
    env_file:
      - ./backend/.env
    networks:
      - proxy-net
    depends_on:
      - mongo
      - redis

  frontend:
    image: abdullah048/portfolio:movie-frontend
    container_name: movies-frontend
    expose:
      - '3000'
    env_file:
      - ./frontend/.env
    networks:
      - proxy-net

volumes:
  mongo-data:
  redis-data:

networks:
  proxy-net:
    external: true
