name: Deploy to Hetzner

on:
  workflow_run:
    workflows: ['CI - Build & Push Docker Images']
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: 🔑 Setup SSH Agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.HETZNER_SSH_KEY }}

      - name: 🚀 Deploy Backend & Frontend
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.HETZNER_USER }}@${{ secrets.HETZNER_HOST }} << 'EOF'
            mkdir -p /srv/movies/backend
            mkdir -p /srv/movies/frontend

            cd /srv/movies/backend
            docker-compose pull
            docker-compose up -d

            cd /srv/movies/frontend
            docker-compose pull
            docker-compose up -d
          EOF
